export const LOGIN_ROUTE = '/login'
export const REGISTER_ROUTE = '/register'
export const APP_CONNECTION_ROUTE = '/connect'
export const CALLBACK_ROUTE = '/callback'
export const MAIN_ROUTE = '/home'
export const SOCIAL_REGISTER_ROUTE = '/finish-register'
export const FRIENDS_ROUTE = '/friends'
